// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwJcwvPzvtqZFizrXdVP9GNfiDsBWAF2Y',
    appId: '1:456365444127:web:6ed78430fb376439b0d92a',
    messagingSenderId: '456365444127',
    projectId: 'blooddonationapp-314d3',
    authDomain: 'blooddonationapp-314d3.firebaseapp.com',
    storageBucket: 'blooddonationapp-314d3.appspot.com',
    measurementId: 'G-VZWDD2VCTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKP_3STC0ypR-k_zaEBNxLH4g7uW9LQGA',
    appId: '1:456365444127:android:0e1fa690980b7587b0d92a',
    messagingSenderId: '456365444127',
    projectId: 'blooddonationapp-314d3',
    storageBucket: 'blooddonationapp-314d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-pIjC02rTmR9RF9HVd7Qufe2uxxbfuYU',
    appId: '1:456365444127:ios:3621b09c359e5f43b0d92a',
    messagingSenderId: '456365444127',
    projectId: 'blooddonationapp-314d3',
    storageBucket: 'blooddonationapp-314d3.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-pIjC02rTmR9RF9HVd7Qufe2uxxbfuYU',
    appId: '1:456365444127:ios:330decc060b81bd7b0d92a',
    messagingSenderId: '456365444127',
    projectId: 'blooddonationapp-314d3',
    storageBucket: 'blooddonationapp-314d3.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp.RunnerTests',
  );
}
